# Build, test, and create portable releases
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and create portable zips
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Upload portable builds
      uses: actions/upload-artifact@v4
      with:
        name: JobTracker-Portable
        path: Portable/JobTracker-*.zip.*
        if-no-files-found: error
